class Tourisms{
  String name, address, description , schedule , ticket, photo;
  List<String> imgUrl;


  Tourisms({
    required this.name,
    required this.address,
    required this.description,
    required this.schedule,
    required this.ticket,
    required this.photo,
    required this.imgUrl

   });
}

var listWisata = [
  Tourisms(
      name: 'Sangiran',
      address: 'Kalijambe, Sragen',
      description: 'Sangiran adalah situs arkeologi di Jawa, Indonesia.[1] Menurut laporan UNESCO (1995) "Sangiran diakui oleh para ilmuwan untuk menjadi salah satu situs yang paling penting di dunia untuk mempelajari fosil manusia, disejajarkan bersama situs Zhoukoudian (Cina), Willandra Lakes (Australia), Olduvai Gorge (Tanzania), dan Sterkfontein (Afrika Selatan), dan lebih baik dalam penemuan daripada yang lain.',
      schedule: '8.00 a.m',
      ticket: '10.000',
      photo: 'assets/img/sangiran.jpg',
      imgUrl: ['http://www.museumindonesia.com/img_editor/sangiran_monumen.jpg',
        'http://www.museumindonesia.com/img_editor/sangiran_kapal.jpg']),
  Tourisms(name: 'Pegunungan Arfak',
      address: 'Manokwari, Papu Barat',
      description: 'Alam yang indah memang sudah tidak aneh di Papua. Kekayaan alam yang begitu mempesona memang tersebar luas di salah satu pulau besar Indonesia ini. Kekaguman ini juga akan kita saksikan ketika kita mengunjungi Danau Anggi di wilayah Manokwari, propinsi Papua Barat. Hamparan hutan hijau yang masih liar, pegunungan yang menjulang tinggi, dan kehidupan pedesaan yang masih tradisional menjadi daya tarik luar biasa atas anugerah tak ternilai dari Tuhan ini.',
      schedule: '8.00 a.m',
      ticket: '20.000',
      photo: 'assets/img/arfak.jpg',
      imgUrl: ['https://www.pesonaindo.com/wp-content/uploads/2015/10/pegunungan-arfak2-1000x530.jpg',
        'https://www.pesonaindo.com/wp-content/uploads/2015/10/pegunungan-arfak-1.jpg']),
  Tourisms(name: 'Kawah Ijen',
      address: 'Bondowoso, Jawa timur',
      description: 'Gunung Ijen adalah sebuah gunung berapi aktif yang terletak di perbatasan antara Kabupaten Banyuwangi dan Kabupaten Bondowoso, Jawa Timur, Indonesia. Gunung ini mempunyai ketinggian 2.443 m dan telah beberapa kali meletus. Kawah biru atau blue fire, fenomena alam yang unik dan hanya dapat dilihat di Kawah Ijen – Banyuwangi saja. Saking indahnya fenomena ini bahkan mengalahkan popularitas matahari terbit di Banyuwangi yang disebut sebagai matahari pertama di Jawa. Tak hanya itu, banyak wisatawan dari berbagai negara rela datang jauh-jauh sekedar untuk melihat penampakan si Api Biru di kawah Ijen.',
      schedule: '8.00 a.m',
      ticket: '20.000',
      photo: 'assets/img/kawah_ijen.jpg',
      imgUrl: ['https://www.pesonaindo.com/wp-content/uploads/2015/10/Kawah-Ijen-1-1140x530.jpg',
        'https://www.pesonaindo.com/wp-content/uploads/2015/10/Kawah-Ijen-2.jpg']),
  Tourisms(name: 'Taman Nasional Baluran',
      address: 'Banyuwangi, Jawa Timur',
      description: 'Taman Nasional Baluran adalah salah satu Taman Nasional di Indonesia yang terletak di wilayah Banyuputih, Situbondo dan Wongsorejo, Banyuwangi (sebelah utara), Jawa Timur, Indonesia. Nama dari Taman Nasional ini diambil dari nama gunung yang berada di daerah ini, yaitu Gunung Baluran.Taman Nasional Baluran memiliki beberapa obyek dan daya tarik wisata alam yang cukup beragam, terdiri dari kombinasi berbagai bentang alam mulai dari ekosistem laut hingga pegunungan, savana, dan keanekaragaman jenis satwa dan tumbuhan.',
      schedule: '8.00 a.m',
      ticket: '20.000',
      photo: 'assets/img/baluran.jpg',
      imgUrl: ['https://www.pesonaindo.com/wp-content/uploads/2015/10/Taman-Nasional-Baluran-1-1140x530.jpg',
        'https://www.pesonaindo.com/wp-content/uploads/2015/10/Taman-Nasional-Baluran-2.jpg']),
  Tourisms(name: 'Festival Gandrung Sewu',
      address: 'Banyuwangi, Jawa Timur',
      description: 'Tarian Gandrung Banyuwangi dibawakan sebagai perwujudan rasa syukur masyarakat setiap habis panen Bentuk kesenian yang didominasi tarian dengan orkestrasi khas ini populer di wilayah Banyuwangi yang terletak di ujung timur Pulau Jawa, dan telah menjadi ciri khas dari wilayah tersebut, hingga tak salah jika Banyuwangi selalu diidentikkan dengan gandrung. Kenyataannya, Banyuwangi sering dijuluki Kota Gandrung dan patung penari gandrung dapat dijumpai di berbagai sudut wilayah Banyuwangi. Tarian kolosal Gandrung Sewu di Pantai Boom Banyuwangi tampil spektakuler. Festival Gandrung Sewu di Pantai Boom pada Sabtu yang akan melibatkan lebih kurang 1.000 penari gandrung.',
      schedule: '8.00 a.m',
      ticket: '20.000',
      photo: 'assets/img/gandrung_sewu.jpg',
      imgUrl: ['https://www.pesonaindo.com/wp-content/uploads/2015/10/Festival-Gandrung-Sewu-2-1140x530.jpg',
        'https://www.pesonaindo.com/wp-content/uploads/2015/10/Festival-Gandrung-Sewu-1.jpg']),
  Tourisms(name: 'Kepulauan Derawan',
      address: 'Kalimantan Timur',
      description: 'Derawan merupakan salah satu kepulauan eksotis yang terletak di Kalimantan Timur. Keindahan alamnya yang mempesona bak surga di bumi, seolah- olah mampu menghipnotis para wisatawan yang berkunjung di sana. Tak hanya para wisatawan domestik saja yang kepincut dengan pesona Derawan, namun wisatawan manca negara juga memiliki andil yang besar di dalamnya. Mereka bahkan tak segan menempuh jarak yang cukup berliku hanya untuk mencapai destinasi di Kalimantan Timur ini. Bagi Anda para pecinta alam, Derawan bisa menjadi destinasi impian dengan sejuta pesona alamnya. Khusus bagi Anda yang hendak menyambangi kepulauan Derawan',
      schedule: '8.00 a.m',
      ticket: '20.000',
      photo: 'assets/img/kepulauan_derawan.jpg',
      imgUrl: ['https://www.pesonaindo.com/wp-content/uploads/2015/08/kepulauan-derawan-1-1140x530.jpg',
        'https://www.pesonaindo.com/wp-content/uploads/2015/08/kepulauan-derawan-2.jpg']),
  Tourisms(name: 'Lava Tour Merapi Jogja',
      address: 'Gunung Merapi, Yogyakarta',
      description: 'Wisata Lava Tour Merapi Jogja memberikan kemudahan untuk para wisatawan untuk melihat lebih dekat beberapa material dari letusan gunung merapi yang telah terjadi beberapa tahun yang lalu. Wisata lava tour ini juga sebenarnya memberikan kemudahan pada wisatawan untuk melihat banker dimana ini adalah tempat bunker perlindungan relawan yang meninggal dan telah dijadikan sebagai monumen. Kegiatan Wisata Lava Tour Merapi Jogja memberikan pemadangan puncak gunung merapi dari jarak lebih kurang 2 km',
      schedule: '8.00 a.m',
      ticket: '20.000',
      photo: 'assets/img/lava_tour.jpg',
      imgUrl: ['https://www.pesonaindo.com/wp-content/uploads/2015/08/Lava-Tour-Merapi-Jogja-2-1140x530.jpg',
        'https://www.pesonaindo.com/wp-content/uploads/2015/08/Lava-Tour-Merapi-Jogja-1.jpg']),
  Tourisms(name: 'Rowo Jombor',
      address: 'Klaten, Jawa Tengah ',
      description: 'Daerah Rawa Jombor dahulu sebetulnya merupakan dataran rendah yang berbentuk cekungan luas dan dikelilingi oleh barisan pegunungan. Hal ini menyebabkan dataran rendah itu sering tergenang air, baik saat musim hujan maupun musim kemarau. Daerah tersebut dinamakan Rawa Jombor karena daerah itu sering tergenang air sehingga disebut rawa dan terletak di Desa Jombor yang kini berubah menjadi Desa Krakitan. Genangan air ini dapat jadi lebih tinggi saat musim hujan dikarenakan dari sisi barat laut terdapat sungai yang bernama Kali Ujung dan kali Dengkeng. Kedua sungai itu selalu meluap saat musim hujan dan selalu mengarah ke Rawa Jombor. Luapan air ini membuat Rowo Jombor semakin meluas dan menggenangi rumah warga serta sawah yang berada disekitarnya sehingga banyak warga yang terpaksa dipindahkan ke tempat yang lebih aman di tepi rawa atau tegalan disekitarnya',
      schedule: '8.00 a.m',
      ticket: '20.000',
      photo: 'assets/img/rowo_jombor.jpg',
      imgUrl: ['https://www.pesonaindo.com/wp-content/uploads/2015/08/Rowo-Jombor-2-1140x530.jpg',
        'https://www.pesonaindo.com/wp-content/uploads/2015/08/Rowo-Jombor-1.jpg']),
  Tourisms(name: 'Pengrajin Batik Solo',
      address: 'Solo, Jawa Tengah',
      description: 'Batik adalah ikon budaya Indonesia sekaligus kerajinan yang mempunyai nilai seni tinggi serta telah menjadi sisi dari kehidupan sosial, budaya, serta kebiasaan orang-orang. Di masa lalu wanita Jawa menjadikan ketrampilan membatik juga sebagai sumber mata pencaharian mereka. Bisa di katakan batik Indonesia telah ada mulai sejak zaman Kerajaan Majapahit serta saat penyebaran Islam di Indonesia. Surakarta atau lebih di kenal dengan sebutan Solo merupakan salah satu kota yang populer dengan wisata kain batiknya di Indonesia.',
      schedule: '8.00 a.m',
      ticket: '20.000',
      photo: 'assets/img/batik_solo.jpg',
      imgUrl: ['https://www.pesonaindo.com/wp-content/uploads/2015/08/Pengrajin-Batik-Solo-2-1140x530.jpg',
        'https://www.pesonaindo.com/wp-content/uploads/2015/08/Pengrajin-Batik-Solo-1.jpg']),
  Tourisms(name: 'Pengrajin Payung Fantasi',
      address: 'Klaten, Jawa Tengah',
      description: 'Desa Kwarasan sendiri terletak sekitar 22 km arah timur laut kota Klaten. Dahulu, begitu memasuki desa ini, payung warna warni penuhi rumah-rumah masyarakat. Di halaman yang luas, payung-payung berjajar dijemur. Selama seharian, beberapa orang desa sibuk memotong serta megelem kertas, melukis gambar bunga, angsa, memotong bilah-bilah bambu untuk jeruji payung. Mereka juga membelah kayu-kayu pohon melinjo, memotongnya, lalu menjemurnya sampai betul-betul kering untuk di buat sebagai kerangka payung. Hampir semua masyarakat di enam dukuh di desa ini berprofesi juga sebagai pembuat payung.',
      schedule: '8.00 a.m',
      ticket: '20.000',
      photo: 'assets/img/payung_fanstasi.jpg',
      imgUrl: ['https://www.pesonaindo.com/wp-content/uploads/2015/08/Pengrajin-Payung-Fantasi-1-1140x530.jpg',
        'https://www.pesonaindo.com/wp-content/uploads/2015/08/Pengrajin-Payung-Fantasi-2.jpg']),
  Tourisms(name: 'Pembuat Gong Solo',
      address: 'Solo, Jawa Tengah',
      description: 'Gong yaitu alat musik yang terbuat dari leburan logam (perunggu dengan tembaga) dengan permukaan yang bundar (dengan atau tanpa ada Pencu).Pembuatan gong di Jawa dikerjakan pada rumah yang disebut Besalen yang berukuran6 x 7 Meter dengan tinggi 7 meter, dinding di buat dari batu bata serta semen lantai dari tanah. Pembuatan gong tak dapat dikerjakan seseorang diri tetapi ditangani oleh 9 – 10 orang yang biasa disebut Pandhe Gong',
      schedule: '8.00 a.m',
      ticket: '20.000',
      photo: 'assets/img/gong_solo.jpg',
      imgUrl: ['https://www.pesonaindo.com/wp-content/uploads/2015/08/Pembuat-Gong-Solo-2-1140x530.jpg',
        'https://www.pesonaindo.com/wp-content/uploads/2015/08/Pembuat-Gong-Solo-1.jpg']),
  Tourisms(name: 'Gunung Rinjani',
      address: 'Rinjani, Lombok',
      description: 'gugus awan di pulau Lombok terasa begitu dekat seakan hendak runtuh dari langit. Deru angin menemani langkah demi langkah menapaki salah satu tanah tertinggi di Indonesia ini. Di kejauhan, terlihat Gunung Rinjani berdiri dengan kokohnya. Menjulang sepanjang setengah dari utara lombok, Gunung Rinjani (3726m), adalah gunung berapi tertinggi kedua Indonesia. Rinjani memiliki nilai spiritiual bagi orang Hindu Bali dan suku sasak. Bagi orang bali, Rinjani adalah satu dari tiga gunung yang disucikan karena dianggap tempat tinggal para dewa, setelah Semeru dan Agung.',
      schedule: '8.00 a.m',
      ticket: '20.000',
      photo: 'assets/img/rinjani.jpg',
      imgUrl: ['https://www.pesonaindo.com/wp-content/uploads/2015/09/Gunung-Rinjani-1-1140x530.jpg',
        'https://www.pesonaindo.com/wp-content/uploads/2015/09/Gunung-Rinjani-2.jpg']),
  Tourisms(name: 'Lombok',
      address: 'Lombok, Nusa Tenggara Barat',
      description: 'Dengan pantai-pantai yang indah nan ajaib, Gunung Agung Rinjani dan kehidupan laut spektakuler yang menarik untuk dijelajah, pulau lombok di Nusa Tenggara Barat memiliki banyak destinasi wisata baik di darat maupun di laut. Tidak heran jika Lombok adalah destinasi terpopuler di Nusa Tenggara Barat.Berkunjunglah ke sini untuk berselancar merasakan ombak besar di pesisir selatan. Tantang nyali Anda dengan mendaki puncak gunung vulkanik. Sewalah sepeda dan sepeda motor untuk berkeliling di sepanjang jalanan ladang padi. Dimana saja Anda ingin meghabiskan waktu, Anda tidak akan kecewa dengan kecantikan alam yang spektakuler di sini.',
      schedule: '8.00 a.m',
      ticket: '20.000',
      photo: 'assets/img/lombok.jpg',
      imgUrl: ['https://www.pesonaindo.com/wp-content/uploads/2015/09/lombok-2-1140x530.jpg',
        'https://www.pesonaindo.com/wp-content/uploads/2015/09/lombok-1.jpg']),
  Tourisms(name: 'Pulai Kei',
      address: 'Kei, Maluku',
      description: 'Kei adalah nama sebuah kepulauan nan amat cantik di Maluku. Indonesia Timur memang sudah banyak berbenah untuk memamerkan keindahan pantai dan pulau-pulau eksotis. Sebutan “Mutiara Hitam Dari Timur” yang disematkan untuk Maluku memang terbukti dengan banyaknya pulau-pulau yang dikelilingi pantai-pantainya yang cantik. Tidak hanya orang Indonesia saja yang memuja Kepulauan Kei, namun penulis Muller pun mengatakan kalau pasir putih di pulau ini sangatlah lembut dan tak ada duanya.',
      schedule: '8.00 a.m',
      ticket: '20.000',
      photo: 'assets/img/pulai_kei.jpg',
      imgUrl: ['https://www.pesonaindo.com/wp-content/uploads/2015/08/pulau-kei-1-1140x530.jpg',
        'https://www.pesonaindo.com/wp-content/uploads/2015/08/pulau-kei-2.jpg']),
  Tourisms(name: 'Festival Lembah Waliem Wamena',
      address: 'Wamena, Papua',
      description: 'Inilah festival luar biasa dan telah menjadi daya tarik pengunjung di Papua. Festival Lembah Baliem awalnya merupakan acara perang antarsuku Dani, Lani, dan Suku Yali sebagai lambang kesuburan dan kesejahteraan. Sebuah festival yang menjadi ajang adu kekuatan antarsuku dan telah berlangsung turun temurun namun tentunya aman untuk Anda nikmati.Festival Lembah Baliem berlangsung selama tiga hari dan diselenggarakan setiap bulan Agustus bertepatan dengan bulan perayaan kemerdekaan Republik Indonesia. Awalnya pertama kali digelar tahun 1989. Yang istimewa bahwa festival ini',
      schedule: '8.00 a.m',
      ticket: '20.000',
      photo: 'assets/img/lembah_aliem.jpg',
      imgUrl: ['https://www.pesonaindo.com/wp-content/uploads/2015/08/Festival-Lembah-Baliem-Wamena-2-1140x530.jpg',
        'https://www.pesonaindo.com/wp-content/uploads/2015/08/Festival-Lembah-Baliem-Wamena-1.jpg']),
];

